config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks, except: %i[edit update show] do
    member { post :toggle }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[toggle destroy]
  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task.update(completed: params[:completed])

    respond_to { |format| format.json { render json: { status: "ok" } } }
  end

  def destroy
    @task.destroy
    render turbo_stream: [turbo_stream.remove(@task)]
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-2 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "mt-2") do |f| %>
  <div class="mb-5">
    <%= f.text_field :description, placeholder: "Add new task", class: "inline-block shadow rounded-md" %>
    <%= f.submit "Save", class: "btn py-2 px-4 rounded-md ml-2 bg-blue-600 text-white hover:bg-blue-800 cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li id="<%= dom_id task %>" class="flex items-center w-full justify-between">
  <%= form_with(model: task, class: "text-lg flex items-center my-3 w-72") do |f| %>
    <%= f.check_box :completed, data: { id: task.id, action: "tasks#toggle" }, class: "w-4 mr-2 h-4 text-green-600 bg-gray-100 border-gray-300 rounded checked:bg-green-500" %>
    <%= task.description %>
  <% end %>
  <%= button_to "Delete", task_path(task), method: :delete, class: "rounded-xl bg-red-50 text-red-600 py-2 px-4 hover:bg-red-200 cursor-pointer"%>
</li>

app/views/tasks/index.html.erb
<h1 class="text-2xl font-bold">Task manager</h1>
<div class="mt-2">
  <%= render 'form', task: @task %>
</div>

<h2 class="font-bold text-lg mb-3">Tasks</h2>
<ul id="tasks" data-controller="tasks">
  <%= render @tasks %>
</ul>